import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from plan_parser import TerraformPlanParser
from ai_analyser import AIAnalyser
from risk_engine  import RiskEngine
from pr_comment   import PRCommentFormatter


def main():
    print("=" * 55)
    print("TF Impact Analyser")
    print("=" * 55)

    plan_path = os.path.join(os.path.dirname(__file__), "plan.json")

    if not os.path.exists(plan_path):
        print(f"plan.json not found at {plan_path}")
        print("Run: terraform show -json tfplan > analyser/plan.json")
        sys.exit(1)

    print("\nStep 1/4: Parsing plan...")
    parser = TerraformPlanParser(plan_path)
    parsed = parser.parse()
    print(f"   +{parsed.total_add} add  ~{parsed.total_change} change  -{parsed.total_destroy} destroy  {parsed.total_replace} replace")

    total = parsed.total_add + parsed.total_change + parsed.total_destroy + parsed.total_replace
    if total == 0:
        print("No changes. Posting clean comment.")
        _no_changes()
        return

    plan_summary = parser.to_summary_dict(parsed)

    print("\nStep 2/4: AI analysis...")
    ai_analysis = AIAnalyser().analyse(plan_summary)
    print(f"   Risk: {ai_analysis.get('overall_risk')}  Confidence: {ai_analysis.get('confidence')}%")

    print("\nStep 3/4: Risk engine...")
    assessment = RiskEngine().assess(parsed, ai_analysis)
    print(f"   Final risk: {assessment.overall_risk}  Flags: {len(assessment.deterministic_flags)}")

    print("\nStep 4/4: Posting PR comment...")
    formatter = PRCommentFormatter()
    body      = formatter.format(ai_analysis, assessment, parsed, plan_summary)
    success   = formatter.post_to_github(body)

    print("\n" + "=" * 55)
    print("Done." if success else "Done (comment printed to log).")
    print("=" * 55)

    if assessment.overall_risk == "CRITICAL":
        print("\nCRITICAL risk — exiting with code 1.")
        print("This PR needs senior engineer approval.")
        sys.exit(1)


def _no_changes():
    body = (
        "## TF Impact Analysis\n\n"
        "No infrastructure changes in this plan. Safe to merge.\n\n"
        "<sub>Generated by tf-impact</sub>"
    )
    PRCommentFormatter().post_to_github(body)


if __name__ == "__main__":
    main()
