name: TF Impact Analysis

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  tf-impact:
    name: Terraform Impact Analysis
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      TF_VERSION: 1.9.0

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-python@v5
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r analyser/requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1
          role-session-name: tf-impact-github-actions

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan -input=false -out=tfplan \
            -var="db_password=DummyPassword123!"
        # db_password is only needed for plan validation.
        # We never actually apply this — plan only.
        # In real projects use GitHub Secrets for this.

      - name: Convert plan to JSON
        working-directory: terraform
        run: terraform show -json tfplan > ../analyser/plan.json

      - name: Run TF Impact Analysis
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python analyser/main.py
